#!/bin/bash

export TOOLBOX_DOCKER_IMAGE=steigr/coreos-toolbox
export TOOLBOX_DOCKER_TAG=latest
export TOOLBOX_USER=root
export DOCKER_HOST=unix:///run/early-docker.sock
TOOLBOX="toolbox --bind=/home:/home --bind=/opt:/opt --bind=/run:/run --bind=/run/docker.sock:/var/run/docker.sock --bind=/etc/systemd:/etc/systemd"
$TOOLBOX node install /opt/lib/node
$TOOLBOX node link modules